name: Langchat
version: '${project.version}'
main: com.nomad.langchat.Main
api-version: 1.18
authors: [ Nomad ]
description: A plugin to use fantasy languages in text chat
commands:
  dwarvish:
    permission: lang.dwarvish
    permission-message: You do not speak this language
